### ISSUE TITLE
SpyAll doesn't work if properties are not enumerable

### ISSUE THREAD

**Issue by bensampaio** [mjeanroy/jasmine-utils#3]
All my prototypes have non enumerable options so they are completely ignored by a `for ... in`. Instead of iterating through the properties I suggest you try to get their names with `Object.getOwnPropertyNames ()`.

**Comment by mjeanroy** [comment]
Hi,
Thanks for reporting the issue. Your proposition seems fine, I just commited the fix (see [here](https://github.com/mjeanroy/jasmine-utils/commit/f058ed6a4be040ebfc9bcddebba2cb1248b466bc)).

I will tag a release, and then publish it on npm (will close the issue when the release is available).

**Comment by mjeanroy** [comment]
Hi, fixed in v0.2.3 (it should be available on npm).

**Comment by bensampaio** [comment]
Hey,

That was fast... And it works! Thanks a lot ;)

**Comment by mjeanroy** [comment]
You're welcome, thanks for your feedback !
